print("Daniel Alejandro García García")
print("Carné: 1665924")
print("18 años, proximamente 19")
print("Residencia: Quetzaltenango")
print("Curso: Introduccion a la ingenieria en informatica y sistemas")
